### ISSUE TITLE
putItem conditional expression problem

### ISSUE THREAD

**Issue by flootr** [epha/model#20]
There is a problem with `putItem()` if we want to replace an item that already exists in the database. My evaluation shows, that the problem is that we send an `ConditionalExpression` on every putItem request.

`lib/sugar/items/create.js`

Our code looks like:
```javascript
var params = {
  Item: item,
  ConditionExpression: condition,
  ExpressionAttributeNames: names,
  ExpressionAttributeValues: values
};

return dynamo.putItem(client, tableName, params);
```

At the moment this leads to a `ConditionalCheckFailedException`. If we only send an `Item` attribute, the behaviour is expected.

Do we need this `ConditionalExpression` or can we leave it out? @Jonas74 @meaku

**Comment by meaku** [comment]
That's actually wanted behavior: We have two different sugar functions on top of putItem with different semantics: 

## create 
Creates an item, but doesn't replace if item already exists. That's why we use the `ConditionExpression` to ensure no item with the given __hash__ and __range__ doesn't exist already. 

## upsert
Creates or replaces and item. Uses putItem internally but doesn't use a condition expression. This means it replaces if it exists and creates if it doesn't exit already. 

Can you add this information in the docs and update the tests accordingly? @flootr?

**Comment by flootr** [comment]
Allright!

**Comment by flootr** [comment]
note for me:
- [] add this information in the docs and update tests accordingly
